# Cloud Run Service Configuration
# This file defines the Cloud Run service configuration for CashGuard

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cashguard
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/cashguard:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        # Firebase Configuration (from Secret Manager)
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: firebase-api-key
              key: latest
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: firebase-auth-domain
              key: latest
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-project-id
              key: latest
        - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: firebase-storage-bucket
              key: latest
        - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: firebase-messaging-sender-id
              key: latest
        - name: NEXT_PUBLIC_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: firebase-app-id
              key: latest
        - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: firebase-measurement-id
              key: latest
        # Gemini API Key (from Secret Manager)
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: latest
        resources:
          limits:
            cpu: '2'
            memory: 1Gi







