export {
  getFirebaseApp,
  getFirebaseAuth,
  getFirestoreDb,
  getFirebaseStorage,
  getFirebasePerformance,
  isFirebaseConfigured,
  saveScanResult,
  getScanHistory,
  getScanById,
  deleteScan,
  saveValidationToHistory,
  getValidationById,
  getValidations,
  subscribeToValidations,
  addCurrencyReference,
  getCurrencyReferences,
  updateCurrencyReference,
  deleteCurrencyReference,
  uploadImageToStorage,
  uploadBase64ToStorage,
  uploadBillImage,
  uploadReferenceImage,
} from './firebase.ts'

